{{- if and .Values.podDisruptionBudget (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "oci-native-ingress-controller.fullname" . }}
  namespace: {{ .Values.deploymentNamespace }}
  labels:
    {{- include "oci-native-ingress-controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "oci-native-ingress-controller.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}